name: E-commerce Backend CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    # NEW STEP: Install your packages directly onto the Ubuntu machine
    - name: Install Dependencies
      run: npm install

    # This step ONLY runs if 'npm test' passes successfully!
    - name: Build Docker Image
      run: docker build -t ecommerce-backend:latest .